### ISSUE TITLE
META Internal Release Checklist

### ISSUE THREAD

**Issue by grahamb** [pacificjamboree/pj19-client-app#1]
The following need to be done in order for initial release with ability to import & assign OOS

- [ ] Create New Adventure
- [ ] Send assignment email to AM (with OOS details)
- [ ] Adventure Manager Dashboard
